errors.go, filclient.go
This is mostly a framework for future improvements around Filclient's error generation. `errors.As` with the `filclient.Error` type, followed by checking the error code, can now be used to discover if an error is of a specific category (currently just `ErrMinerConnectionFailed` and `ErrLotusError`). The current set of errors should probably be expanded on over time.
A couple lines will need to be modified in Estuary to accommodate this change.
=> Improved errors

filclient.go
To avoid graphsync allocator locks, we should follow this basic formula
MaxMemoryResponder >= MaxMemoryPerPeerResponder * MaxInProgressRequests
Essentially we need to make sure the total memory allocated for graphsync is greater or equal to the total memory per peer times the number of simultaneous requests. That way, even when serving the maximum number of simultaneous requests, there's no likelyhood, assuming everything is running properly, that we will max out the allocator.
=> Tune graphsync max memory per peer

filclient.go, go.mod, go.sum
Open the floodgates of data transfer, or at least figure out why they're not opening
Update for v0.10.3 of go-graphsync.
v0.10.3 has the following new configs that are used:
MaxInProgressIncomingRequestsPerPeer - set this at 20, which feels appropriate given that it's the default max a storage provider will do anyway for storage. This will prevent a single bad peer from dominating the transfer queue.
MessageSendRetries/SendMessageTimeout - this controls how long we take to fail at sending messages. Previously, these values were VERY HIGH. 10 minutes timeout + 10 retries. This sets it to numbers similar to Bitswap -- 2 minutes to try to send + 1 retry (BS takes one more attempt at sneding for want lists but actually does no retries for actual blocks)
Graphsync v0.10.3 also exposes some …
=> Update for 0.10.3 with better tuning and stats

filclient.go
microscopic change, will make sure data transfers are always closed even if cancelled
=> close data transfer channel at end of retrieval

go.mod, go.sum
v0.10.8 broke request counts on the Stats method, this fixes it. Also v0.10.9 release happens to also have tracing for responses, which should generate interesting data.
Updating in Estuary itself after merge is left as an exercise for the reader.
=> Update graphsync with minor fix

go.mod, go.sum
Ooops! I forgot to update go-data-transfer to adjust to the new changes in one of the graphsnyc hooks
=> Update to compilable data transfer

filc/cmds.go, filc/flags.go, filc/retrieval.go
contains a bit of a nicer and more flexible framework for specifying network attempt order
=> Replace `--no-ipfs [true|false]` flag with `--network [fil|ipfs|auto]`

filc/retrieval.go
if a retrieval succeeds, for instance over IPFS, currently `RetrieveFromBestCandidate` will keep going and try with the next candidate anyway (i.e. FIL), causing potentially multiple retrievals and seemingly failing under all circumstances.
in `filc` that means that the content is downloaded over IPFS, but is never saved locally if the FIL content retrieval fails.
I tested this by using `./filc/filc retrieve <locally pinned IPFS CID>`
=> fix: stop after the 1st successful retrieval

filclient.go
Allow retrieval when you only have a peer.AddrInfo. This is aimed to support autoretrieve fetching content that is listed in content indexers rather than Estuary.
- Promote minerPeer to MinerPeer public method that returns a peer.AddrInfo
- Add a "streemToPeer" function & "connectToPeer" function to parallel "streamToMiner" and "connectToMiner"
- Add a version of RetrievalQuery --> RetrievalQueryFromPeer that runs with just a peer.AddrInfo
- Add a version of RetrieveContextWithProgressCallback --> RetrieveContentFromPeerWithProgressCallback that runs with just a peer.AddrInfo
-  This PR could be a lot simpler if it dropped support for retrieval methods via miner address and moved the calls to MinerPeer/minerOwner directly into estuary -- I wanted to maintain backward compatibility for now …
=> Expose retrieval via peerAddr + wallet only

filclient.go, go.mod, go.sum
This PR updates go-graphsync and go-data-transfer. From the standpoint of filclient, it's very small. However, the 0.13.0 version of go-graphsync includes significant changes. You can see them in go-graphsync's CHANGELOG here: https://github.com/ipfs/go-graphsync/blob/main/CHANGELOG.md
The only changes in filclient other than go.mod updates are that GraphSync has a new ID type for Requests -- they are now UUIDs. I made a small change to the MinerTransferDiagnostics API, which I'm pretty sure no one but me knows about or uses anyway :)
=> Update graphsync 0.13.0 with 2.0 protocol

filclient.go
Make sure retrievals only finish once all blocks are received
Under certain conditions, a provider may send back their "DealComplete" message before all blocks are processed by the received. Ultimately, this is a bit of a race of things happening that really needs to be fixed in go-data-transfer (but it's not super easy to fix). However, for now, this copies the logic of go-fil-markets, which says to be done, the provider must tell us the deal is complete AND we must verify that the transfer has completed.
=> Fix completion condition 

filc/cmds.go, filc/main.go, filc/printing.go
`filc deal-status --miner <miner address> <proposal cid>`
i tested some deals from filexplorer but they all seemed to be errored. not sure if this is a mistake i made in code or if it was actually accurate. if someone's able to try this with a known working deal id, that'd be great!
=> feat(filc): deal-status subcommand

filclient.go
In Estuary, this is needed to track the various data transfer stages and their timestamps. This info can be used to set the data transfer completed timestamp (`transfer_finished` in the Estuary database). Right now, in the `content_deal` table, the `transfer_finished` column is not populated when a deal is sealed. This column is set at https://github.com/application-research/estuary/blob/master/replication.go#L1711
I have tested this by calling `TransferStatus(ctx, &chanid)` and I was able to get the timestamp for `transfer_finished` stage 
```
chanst, _ := cm.FilClient.TransferStatus(ctx, &chanid)
for _, s := range chanst.Stages.Stages {
spew.Dump(s.Name, s.CreatedTime.Time(),)
}
// output
stage - (string) (len=16) "TransferFinished"
created_at - (time.Time) 2022-02-07 14:08:02.00764 …
```
=> Add datatransfer stages to ChannelState

filclient.go
The first retrieval by RetrieveContent successfully retrieves the file, but more calls fail to retrieve it.
=> fix multiple retrieve fail

rep/publisher_test.go
Show the panic that occurs if you attempt to subscribe with a value that is not comparable.
=> Add test to demonstrate panic

filclient.go
When `receivedFirstByte` is declared, it's inside the event callback, so it's getting set initialized as false every time a new `DataReceivedProgress` state comes in.
=> fix: rescope receivedFirstByte bool to prevent unwanted reinitialization

filclient.go, rep/event.go
This is #87 but with a local branch so I can use it in autoretrieve now I have access.
It's primarily to serve https://github.com/application-research/filclient/pull/87
@hannahhoward has a valid critique of the weirdness of `QueryResponse` hanging off the event, but I'd like to suggest we move forward with this awkward stage and come back and clean it up in a second pass, just so we can get the autoretrieve event reporting over the line.
What I'd like to do is make the `RetrievalState` object go away and pack all of the useful information into the event object, _but_ use a typed event object for each event type. Then for some of the specific types we can attach additional data to them (errors, `QueryResponse` and some retrieval success data).
=> Expand and fix event reporting

filclient.go, libp2ptransfermgr.go
On methods that return channel state, distinguish between Boost transfers and Graphsync transfers
(for future metrics)
=> Record transfer type in channel state

filclient.go, rep/event.go, rep/publisher.go, rep/publisher_test.go, rep/subscriber.go
Draft for now, an attempt at reworking the event system now that autoretrieve is the only consumer. I've done away with the "status" object and have introduced typed events which are all the same but 3 have additional, specific fields: query-ask, failure & success. So for each of those, you can type cast and access the additional info.
I wanted to get this up so suggest how we could move beyond the awkwardness in #88 of hanging the `QueryResponse` in the event. But this PR isn't critical to get the autoretrieve work over the line, so I'm suggesting we merge #88 and treat this as a second stage of work.
=> feat: rework retrieval events

filclient.go
Fixes: https://github.com/application-research/filclient/issues/96
@hannahhoward is this the kind of thing we need to be doing?
I note there's already one `Protect()` call in `StartDataTransfer` with a `"transferring"` tag, but no corresponding `Unprotect()`; is that safe since ended connections are unprotected anyway? So are these `Unprotect` calls I've added even necessary?
=> fix: protect libp2p connections while querying

filc/disk.go, go.mod, go.sum
This replaces filc's use of lmdb with flatfs (which is already imported as a dependency)
this is a breaking change. existing filc blockstores will not work anymore and will need to be reset (using `filc clear-blockstore`). I think this is acceptable because lmdb is currently holding up filclient dependency upgrades and is unmaintained and its dependencies are also unmaintained and yeah we really just need to get rid of it.
if upon next filclient release people really do care about the contents of their blockstores, i can write a migration script that will convert the filc lmdb blockstore to flatfs.
=> BREAKING CHANGE: remove lmdb

filclient.go, rep/event.go, rep/publisher_test.go
* check for potential data transfer errors, where DT reports success but the block(s) we wanted didn't end up in our blockstore. Ref: https://github.com/application-research/autoretrieve/pull/121
* add more info on success event
These two commits are not strictly related. As I was refactoring in autoretrieve to deal with the block-unconfirmed case I found I wanted more reporting data, so I'd added it in here, and then I decided that filclient was a better place to do the block confirmation anyway.
So this deals with the case where data transfer doesn't properly report on the status of a retrieval—it's possible to get "success" but no blocks transferred and the block(s) we want not being in the blockstore (i.e. no blocks being transferred is valid if we already had what we wanted). Doing …
=> Confirm block(s) received, and add additional reporting data

retrievehelper/params.go
Ref: https://github.com/application-research/autoretrieve/issues/120
SP's record retrieval deals unique by peer ID and deal ID. If a single peer makes enough retrievals to a single SP with a small unique deal ID space and they start to be reused then we can experience failures as the SP gets confused about what retrieval deal they're dealing with.
Current implementation here has a relatively small space, which is apparently getting exhausted by autoretrieve which makes a _lot_ of deals with any SP that will talk to it. This seems to be the cause of the large number of failures with:
data transfer failed: datatransfer error: response rejected
This fix uses the deal ID generator from go-fil-markets that uses a monotonic set of IDs starting from the unixtime of instantiation. If no two …
=> fix: improve uniqueness of DealID for retrievals

filclient.go
We rely on having error events for all errors (except context closes) to track active retrievals in autoretrieve, without accounting for them all we can get leaks. I doubt these ones are actually occurring but we should add them for completeness, just in case.
=> fix: more error event reporting

filclient.go
Adds a function that runs retrieval asynchronously, allowing a user to request a graceful shutdown
=> Add async retrieval function

filc/cmds.go, filc/flags.go, filc/parsing.go, filclient.go, filclient_test.go
Allow consumers of filclient to pass a removeUnsealed parameter into MakeDeal, which sets the corresponding flag in the deal proposal. 
This allows filclient users to communicate whether or not they want SPs to store an unsealed copy.
When used via cli, filclient will default to `removeUnsealed = false`, which is consistent with boost's default. When calling MakeDeal, a value must be provided explicitly.
=> Expose option to set removeUnsealed when calling MakeDeal

filclient.go
this change allows for a v120 proposal's transfer parameters to be modified. at the same time, i have wrapped up these configuration points into a variadic option pattern for better accessibility.
i have not tested this directly, but it's intended to be used in [delta](https://github.com/application-research/delta) and we should be able to verify functionality there!
example usage:
```go
fc.SendProposalV120WithOptions(
ctx,
netprop,
ProposalV120WithDealUUID(dealUUID),
ProposalV120WithLibp2pTransfer(announce, authToken, dbid),
)
```
if no transfer-related option is passed, the announce parameters will be left empty. to pass custom raw transfer params, use option `ProposalV120WithTransfer(smtypes.Transfer)`
=> feat: v120 proposal extended config with accessible transfer options

filclient.go
this uses the same variadic options pattern as #153 to provide an extensible interface for optional deal creation settings.
example
```go
fc.MakeDealWithOptions(
ctx,
sp,
payloadCid,
price,
duration,
DealWithVerified(true),
DealWithFastRetrieval(true),
DealWithPieceInfo(PieceInfo{
cid: myPrecomputedPieceCid,
size: myPrecomputedPieceSize,
payloadSize: myPrecomputedPayloadSize,
}),
)
```
needs to be tested in delta
=> feat: extended deal config
